name: autoformat-and-lint

on:
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]
  
jobs:
  format-and-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
      
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Format with black
      run: black **.py
      continue-on-error: true

    - name: Install ruff
      run: python -m pip install ruff
    
    - name: Lint with ruff
      run: ruff check --fix
