name: check-types

on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["**"]


jobs:
  check-types:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Setup pdm
      run: |
        pip install pdm
        pdm add --dev pyright
        pdm install

    - name: Check types using pyright
      run: pdm run pyright src
