name: Python Package Test with Tox

on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["**"]

jobs:
  tox-tests:
    name: tox-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.0, 3.12.1, 3.12.2, 3.12.3]

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start postgres container
      run: docker compose -f .containers/postgres-container/docker-compose.yml up -d

    - name: Install PDM
      run: |
        pip install pdm
        pdm install

    - name: Install dependencies and tox with PDM
      run: |
        pdm install

    - name: Run Tox
      run: |
        pdm run tox
